# 高考志愿填报助手系统配置文件
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: gaokao-helper
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gaokaodb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&connectionCollation=utf8_bin&allowPublicKeyRetrieval=true
    username: root
    password: 114514
    # HikariCP连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      pool-name: GaokaoHelperHikariCP
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update  # 恢复为update，保持表结构更新
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# 日志配置
logging:
  level:
    com.gaokao.helper: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gaokao-helper.log

# Actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# 应用信息
info:
  app:
    name: 高考志愿填报助手系统
    description: 为高考生提供科学的志愿填报建议和相关查询服务
    version: 1.0.0
    author: PLeiA

# JWT配置
jwt:
  secret: gaokao-helper-jwt-secret-key-2024-this-is-a-very-long-secret-key-for-hs512-algorithm-security
  expiration: 86400000 # 24小时，单位毫秒

# 自定义配置
gaokao:
  helper:
    # 缓存配置
    cache:
      default-ttl: 3600 # 默认缓存时间，单位秒
    # 算法配置
    algorithm:
      prediction:
        history-years: 5 # 预测算法使用的历史年份数
        weight:
          statistical: 0.6 # 统计模型权重
          ml: 0.4 # 机器学习模型权重
    # API限流配置
    rate-limit:
      enabled: true
      requests-per-minute: 100
    # AI对话配置
    ai:
      deepseek:
        api-key: sk-0731d87eb4fb4f489094a7f4316ada2a
        base-url: https://api.deepseek.com
        model: deepseek-chat
        max-tokens: 2000
        temperature: 0.7
        timeout: 90000 # 延长到90秒超时 (原来30秒)
        max-retries: 5 # 增加重试次数到5次
